name: Dependa-bolt
description: Make sure all packages in a bolt-managed monorepo are updated via Dependabot (not affiliated with Dependabot or bolt)
branding:
  icon: package
  color: gray-dark
inputs:
  gitCommitEmail:
    description: The email to use when committing to the repository, defaults to the repository owner's fake GitHub email.
    required: false
    default: ''
  gitCommitFlags:
    description: 'Any extra `git commit` flags to pass, such as `--no-verify`.'
    default: ''
    required: false
  gitCommitUser:
    description: 'The value to set `git config user.name`, defaults to the repository owner.'
    required: false
runs:
  using: composite
  steps:
    name: Run Dependabolt
    shell: bash
    run: $GITHUB_ACTION_PATH/entrypoint.sh
